---
baseURL: https://beta.particl.wiki/ # <---------- update before release!
title: Particl Project Wiki
#theme: hugo-geekdoc
pygmentsUseClasses: true
pygmentsCodeFences: true

# Geekdoc configuration
disablePathToLower: true
enableGitInfo: true # grabs modified date for articles (https://gohugo.io/variables/git/) and more

# Needed for mermaid shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

params:
  # (Optional, default 6) Set how many table of contents levels to be showed on page.
  # Use false to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
  # You can also specify this parameter per page in front matter.
  geekdocToC: 2

  # (Optional, default static/brand.svg) Set the path to a logo for the Geekdoc
  # relative to your 'static/' folder.
  geekdocLogo: particl-wiki-symbol.svg

  # (Optional, default false) Render menu from data file im 'data/menu/main.yaml'.
  #geekdocMenuBundle: true

  geekdocRepo: https://github.com/AllienWorks/particl-wiki
  geekdocEditPath: edit/master/content

  geekdocDateFormat: "Jan 2, 2006"

  # (Optional, default true) Enables search function with flexsearch.
  # Index is built on the fly and might slowdown your website.
  geekdocSearch: true

  # (Optional, default true) Add an anchor link to headlines.
  geekdocAnchor: true

  # (Optional, default true) Copy anchor url to clipboard on click.
  geekdocAnchorCopy: true

  #geekdocLegalNotice: https://thegeeklab.de/legal-notice/#contact-information
  #geekdocPrivacyPolicy: https://thegeeklab.de/legal-notice/#privacy-policy



# Privacy enhancements (https://gohugo.io/about/hugo-and-gdpr/)
privacy:
  youtube:
    privacyEnhanced: true
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true